### ISSUE TITLE
Unexpected token ...

### ISSUE THREAD

**Issue by rikochet** [enhancv/braintree-as-promised#5]
I'm new to Node.js and getting an unexpected token error... Any ideas what I am doing wrong?

Used sample code;

```
gateway.clientToken
    .generate({})
    .then((result) => {
        console.log(result.clientToken);
    });
```

Returned the following error;

```
./app/node_modules/braintree-as-promised/src/promised.js:18
            object[method](...arguments, callback);
                           ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
   at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (./app/src/controllers/Payments.js:7:18)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (./app/src/routes/payments.js:4:27)
    at Module._compile (module.js:435:26)

```

**Comment by rikochet** [comment]
Ok this was just me being stupid.. Turns out the version npm was pulling down is not your ES5 version.. Now that I am pulling the latest master everything works great!
